**1. Import NumPy Library as np**

In [1]:
import numpy as np

**2. Create an array of integers starting from 15 to 40 and store it in a variable called array1**

In [2]:
array1 = np.arange(15,41)
array1

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40])

**2.1. Create a second array of integers starting from 10 until 25 and store it in a variable called array2**

In [3]:
array2 = np.arange(10,26)
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

**2.2. What is the difference between the two arrays?**

In [4]:
print(np.setdiff1d(array1, array2))

[26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]


**3. Create an array of all even integers from 2 to 20 and name it even_array1**

In [5]:
even_array1 = np.arange(2, 21, 2)
even_array1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

**3.1. Create an array of all even integers from 34 to 42 and name it even_array2**

In [6]:
even_array2 = np.arange(34, 43, 2)
even_array2

array([34, 36, 38, 40, 42])

**3.2. Create a matrix of the two arrays using the stack function**

In [7]:
even_array1_1 = even_array1[0:5]
even_array1_2 = even_array1[5:10]
stack_array = np.stack((even_array1_1, even_array1_2, even_array2), axis=0)
stack_array

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [34, 36, 38, 40, 42]])

**4. Create a 6×6 matrix with values ranging from 0 to 36 and retrieve the intersection of the 3rd row and 2nd column**

In [8]:
my_array = np.arange(36)
my_array.resize(6,6)
my_array[2,1]

13

**4.1. Create a 5×2 matrix from a standard normal distribution generated with python.**

In [9]:
rand_array = np.random.rand(5,2)
rand_array

array([[0.69855818, 0.17885299],
       [0.19833286, 0.18265138],
       [0.49210876, 0.37568805],
       [0.39160347, 0.70189349],
       [0.90051794, 0.71823748]])

**4.2. Retrieve the value intersecting the last row and the last column of your matrix**

In [10]:
rand_array[-1,-1]

0.7182374837636055

**5. Using your matrix created at 4.1, calculate the following:**

**a. minimum of the matrix**

In [11]:
np.min(rand_array)

0.17885298739408906

**b. maximum of the matrix**

In [12]:
np.max(rand_array)

0.9005179372922179

**c. standard deviation of the matrix**

In [13]:
np.std(rand_array)

0.24652235083102159

**d. variance of the matrix**

In [14]:
np.var(rand_array)

0.060773269459253286

**e. mean of the matrix**

In [15]:
np.mean(rand_array)

0.48384445956409794